"""convert_to_uuid

Revision ID: 6b0e7abdc55b
Revises: 
Create Date: 2026-02-09 15:15:07.923417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6b0e7abdc55b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_employees_employeeId'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employeeId', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('mobileNo', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('centerId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('onBoardingStatus', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('roles', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('reportingOfficerId', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['reportingOfficerId'], ['employees.employeeId'], name=op.f('FK__employees__repor__5AEE82B9')),
    sa.PrimaryKeyConstraint('employeeId', name=op.f('PK__employee__C134C9C1DF547F0C'))
    )
    op.create_index(op.f('ix_employees_employeeId'), 'employees', ['employeeId'], unique=False)
    op.create_table('leaves',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('employeeId', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True),
    sa.Column('leaveTypeId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fromDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('toDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('leaveSession', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('financialYearId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approvedBy', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True),
    sa.Column('approvalComments', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approvedBy'], ['employees.employeeId'], name=op.f('FK__leaves__approved__5EBF139D')),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.employeeId'], name=op.f('FK__leaves__employee__5DCAEF64')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__leaves__3213E83F84121AC0'))
    )
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    # ### end Alembic commands ###
